spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://ep-fancy-poetry-aovat19y.c-2.ap-southeast-1.aws.neon.tech/app_user_db?sslmode=require&channelBinding=require
    username: neondb_owner
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always #when_authorized
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 8081

logging:
  level:
    root: INFO
    com.bigapplication.userservice: INFO
    com.bigapplication.userservice.security.JwtAuthenticationFilter: DEBUG

app:
  jwt:
    issuer: user-service
    secret: ${JWT_SECRET}
    access-token-expiration-minutes: 60
    refresh-token-expiration-minutes: 10080
